import { Box, Image, Text } from '@chakra-ui/react';
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import styles from "../styles/Home.module.css";

// feed
// tweets of other people you follow
// [tweets] => [User usr, str message]

var tweets = [
  { id: 1 ,username: "Nali" , message: "Hi Scrubs. This is my first tweet." },
  { id: 2, username: "Martin" , message: "Happy New Year!" },
  { id: 3, username: "Mert" , message: "Get me off, this platform, i'm tired" },
];

function IncrementComponent() {
  const [counter, setCounter] = useState(0);
  function increment() {
    setCounter(counter + 1);
  }
  return (
    <div>
      {" "}
      <p>{counter}</p> <img src="/monobono.jpeg" />
      <button onClick={increment}> Increment </button>
    </div>
  );
}

// Sample card from Airbnb

function TweetComponent({tweet}) {

  const tweetProperties = {
    imageUrl: '/monobono.jpeg',
    imageAlt: 'profile pic',
    message: tweet.message,
    sender: tweet.username,
  }
  
  return (
    <Box maxW='sm' borderWidth='1px' borderRadius='lg' overflow='hidden' padding='5' marginBottom={5}>
      <Image src={tweetProperties.imageUrl} alt={tweetProperties.imageAlt} />

      <Box p='2'>
        <Box display='flex' alignItems='baseline'>
          <Box
            color='gray.500'
            fontWeight='semibold'
            letterSpacing='wide'
            fontSize='inherit'
          >
            {tweetProperties.sender}
          </Box>
        </Box>

        <Box
          mt='1'
          fontWeight='semibold'
          as='h4'
          lineHeight='tight'
          isTruncated
        >
          <Text wrap='wrap'>{tweetProperties.message}</Text>
          
        </Box>

        <Box color='teal.500'>
        <Link  href={{ pathname: "/profile",
                      query: tweetProperties }}>Click to go to profile</Link>
          {/* {tweetProperties.formattedPrice} */}
          <Box as='span' color='gray.600' fontSize='sm'>
          </Box>
        </Box>

        <Box display='flex' mt='2' alignItems='center'>
          <Box as='span' ml='2' color='gray.600' fontSize='sm'>
            {/* {tweetProperties.reviewCount} reviews */}
          </Box>
        </Box>
      </Box>
    </Box>
  )
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Twali
        </h1>
        {tweets.map(element => {
           return <TweetComponent key={element.id} tweet={element} />
        })}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
